# Generated by Django 5.1 on 2024-09-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0002_alter_answer_options_game_current_answer_player_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="button_id",
            field=models.IntegerField(default=0),
        ),
    ]
